<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-1OUCR3EM" failures="1" tests="1" name="FirefoxTest(failed)" time="10.912" errors="0" timestamp="2022-05-28T14:33:42 IST">
  <testcase classname="testjava.TestNgprac" name="verifydrop" time="0.503">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/inventory.htmp]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/inventory.htmp]
at testjava.TestNgprac.verifydrop(TestNgprac.java:84)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifydrop -->
  <testcase classname="testjava.TestNgprac" name="verifyaddcart" time="0.0">
    <ignored/>
  </testcase> <!-- verifyaddcart -->
</testsuite> <!-- FirefoxTest(failed) -->
